// AUTO-GENERATED by scripts/gen-master-data.mjs — do not edit by hand.
// Source: data/master/*.csv (master reference data supplied by KYN, 24 Aug 2026).

export interface FlowerEntry {
  category: string; categoryEn: string;
  type: string; typeEn: string;
  variant: string; variantEn: string;
}

/** 85 varieties across 28 types — thailand_cut_flowers_list */
export const FLOWERS: FlowerEntry[] = [
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เบญจมาศ", typeEn: "Chrysanthemum", variant: "มูลันสีชมพู", variantEn: "Mulan Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เบญจมาศ", typeEn: "Chrysanthemum", variant: "เรดดีสีแดง", variantEn: "Reddy Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เบญจมาศ", typeEn: "Chrysanthemum", variant: "กระดุมสีเขียว", variantEn: "Green Button" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เบญจมาศ", typeEn: "Chrysanthemum", variant: "ขาวมาเลเซียสีขาว", variantEn: "Malaysian White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เบญจมาศ", typeEn: "Chrysanthemum", variant: "เหลืองขมิ้นสีเหลือง", variantEn: "Khamin Yellow" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กุหลาบ", typeEn: "Rose", variant: "แบ็กคาร่าสีแดงเข้ม", variantEn: "Black Baccara Dark Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กุหลาบ", typeEn: "Rose", variant: "อวาลานช์สีขาว", variantEn: "Avalanche White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กุหลาบ", typeEn: "Rose", variant: "โซเฟียลอเรนสีชมพู", variantEn: "Sophia Loren Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กุหลาบ", typeEn: "Rose", variant: "ว้าวสีส้ม", variantEn: "Wow Orange" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กุหลาบ", typeEn: "Rose", variant: "ไร้หนามโครงการหลวงสีชมพูพาสเทล", variantEn: "Royal Project Thornless Pastel Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กล้วยไม้", typeEn: "Orchid", variant: "หวายสีโจแดง", variantEn: "Dendrobium Jo Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กล้วยไม้", typeEn: "Orchid", variant: "หวายสีบอมชมพู", variantEn: "Dendrobium Bom Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กล้วยไม้", typeEn: "Orchid", variant: "หวายสีขาวสนาน", variantEn: "Dendrobium Sanan White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กล้วยไม้", typeEn: "Orchid", variant: "แวนด้าสีส้ม", variantEn: "Vanda Orange" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กล้วยไม้", typeEn: "Orchid", variant: "ออนซิเดียมสีเหลืองทอง", variantEn: "Oncidium Golden Yellow" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เยอบีร่า", typeEn: "Gerbera", variant: "เรดร็อคสีแดง", variantEn: "Red Rock Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เยอบีร่า", typeEn: "Gerbera", variant: "ดักลาสสีเหลือง", variantEn: "Douglas Yellow" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เยอบีร่า", typeEn: "Gerbera", variant: "ออโรร่าสีส้ม", variantEn: "Aurora Orange" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เยอบีร่า", typeEn: "Gerbera", variant: "นาตาชาสีชมพู", variantEn: "Natasha Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ลิลลี่", typeEn: "Lily", variant: "คาซาบลังก้าสีขาว", variantEn: "Casablanca White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ลิลลี่", typeEn: "Lily", variant: "ซอร์บอนน์สีชมพู", variantEn: "Sorbonne Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ลิลลี่", typeEn: "Lily", variant: "ทีโบว์สีเหลือง", variantEn: "Teepee Yellow" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ปทุมมา", typeEn: "Siam Tulip", variant: "เชียงใหม่พิงค์สีชมพู", variantEn: "Chiang Mai Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ปทุมมา", typeEn: "Siam Tulip", variant: "ขาวมุกสีขาว", variantEn: "Pearl White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ปทุมมา", typeEn: "Siam Tulip", variant: "ลัดดาวรรณสีแดง", variantEn: "Laddawan Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ปทุมมา", typeEn: "Siam Tulip", variant: "ช็อคโกแลตสีน้ำตาลแดง", variantEn: "Chocolate Red-Brown" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "หน้าวัว", typeEn: "Anthurium", variant: "เปลวเทียนสีแดง", variantEn: "Plew Thian Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "หน้าวัว", typeEn: "Anthurium", variant: "ดารินสีชมพู", variantEn: "Darin Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "หน้าวัว", typeEn: "Anthurium", variant: "ขาวดวงตาสีขาว", variantEn: "Khao Duangta White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "หน้าวัว", typeEn: "Anthurium", variant: "เอลซ่าสีเขียว", variantEn: "Elsa Green" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "คาร์เนชัน", typeEn: "Carnation", variant: "คาร์เนชันสีชมพูคลาสสิก", variantEn: "Classic Pink Carnation" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "คาร์เนชัน", typeEn: "Carnation", variant: "คาร์เนชันสีแดงสเปน", variantEn: "Spanish Red Carnation" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "คาร์เนชัน", typeEn: "Carnation", variant: "คาร์เนชันสีส้มพีช", variantEn: "Peach Orange Carnation" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "คาร์เนชัน", typeEn: "Carnation", variant: "คาร์เนชันสีเขียวแอปเปิ้ล", variantEn: "Apple Green Carnation" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ทานตะวัน", typeEn: "Sunflower", variant: "วินเซนต์ชอยส์สีส้มทอง", variantEn: "Vincent Choice Orange-Gold" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ทานตะวัน", typeEn: "Sunflower", variant: "ซันริชสีเหลืองเข้ม", variantEn: "Sunrich Deep Yellow" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "มากาเร็ต", typeEn: "Margaret", variant: "มากาเร็ตสีม่วงเข้ม", variantEn: "Deep Purple Margaret" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "มากาเร็ต", typeEn: "Margaret", variant: "มากาเร็ตสีม่วงอ่อน", variantEn: "Light Purple Margaret" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "มากาเร็ต", typeEn: "Margaret", variant: "มากาเร็ตสีชมพู", variantEn: "Pink Margaret" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "มากาเร็ต", typeEn: "Margaret", variant: "มากาเร็ตสีขาว", variantEn: "White Margaret" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "คัตเตอร์ / พีค็อก", typeEn: "Cutter & Peacock", variant: "คัตเตอร์สีขาว", variantEn: "White Cutter" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "คัตเตอร์ / พีค็อก", typeEn: "Cutter & Peacock", variant: "พีค็อกสีม่วง", variantEn: "Purple Peacock" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "คัตเตอร์ / พีค็อก", typeEn: "Cutter & Peacock", variant: "พีค็อกสีชมพู", variantEn: "Pink Peacock" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ยิปโซ / ยิปซี", typeEn: "Gypsophila", variant: "ยิปโซสีขาว", variantEn: "White Gypsophila" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ยิปโซ / ยิปซี", typeEn: "Gypsophila", variant: "ยิปซีสีชมพู", variantEn: "Pink Gypsy" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ยิปโซ / ยิปซี", typeEn: "Gypsophila", variant: "ยิปโซย้อมสีรุ้ง", variantEn: "Rainbow Dyed Gypsophila" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแตติส", typeEn: "Statice", variant: "สแตติสสีม่วงเข้ม", variantEn: "Deep Purple Statice" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแตติส", typeEn: "Statice", variant: "สแตติสสีชมพู", variantEn: "Pink Statice" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแตติส", typeEn: "Statice", variant: "สแตติสสีเหลือง", variantEn: "Yellow Statice" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแตติส", typeEn: "Statice", variant: "สแตติสสีขาว", variantEn: "White Statice" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ไฮเดรนเยีย", typeEn: "Hydrangea", variant: "ไฮเดรนเยียสีฟ้าอ่อน", variantEn: "Light Blue Hydrangea" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ไฮเดรนเยีย", typeEn: "Hydrangea", variant: "ไฮเดรนเยียสีชมพูม่วง", variantEn: "Pink Purple Hydrangea" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ไฮเดรนเยีย", typeEn: "Hydrangea", variant: "ไฮเดรนเยียสีขาว", variantEn: "White Hydrangea" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "อัลสโตรมีเรีย", typeEn: "Alstroemeria", variant: "อัลสโตรมีเรียสีชมพูลายเสือ", variantEn: "Tiger Pink Alstroemeria" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "อัลสโตรมีเรีย", typeEn: "Alstroemeria", variant: "อัลสโตรมีเรียสีขาวปากเหลือง", variantEn: "White Yellow Lip Alstroemeria" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "อัลสโตรมีเรีย", typeEn: "Alstroemeria", variant: "อัลสโตรมีเรียสีม่วงพาสเทล", variantEn: "Pastel Purple Alstroemeria" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแน็ปดรากอน / ปากมังกร", typeEn: "Snapdragon", variant: "สแน็ปดรากอนสีชมพูเข้ม", variantEn: "Deep Pink Snapdragon" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแน็ปดรากอน / ปากมังกร", typeEn: "Snapdragon", variant: "สแน็ปดรากอนสีเหลืองเลมอน", variantEn: "Lemon Yellow Snapdragon" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแน็ปดรากอน / ปากมังกร", typeEn: "Snapdragon", variant: "สแน็ปดรากอนสีขาวนวล", variantEn: "Off-White Snapdragon" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "แกลดิโอลัส / ดอกซ่อนกลิ่นฝรั่ง", typeEn: "Gladiolus", variant: "แกลดิโอลัสสีแดงสด", variantEn: "Bright Red Gladiolus" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "แกลดิโอลัส / ดอกซ่อนกลิ่นฝรั่ง", typeEn: "Gladiolus", variant: "แกลดิโอลัสสีชมพูอมส้ม", variantEn: "Peach Pink Gladiolus" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "แกลดิโอลัส / ดอกซ่อนกลิ่นฝรั่ง", typeEn: "Gladiolus", variant: "แกลดิโอลัสสีเหลืองทอง", variantEn: "Golden Yellow Gladiolus" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สร้อยทอง", typeEn: "Solidago", variant: "สร้อยทองสีเหลือง", variantEn: "Solidago Yellow" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ดาวเรือง", typeEn: "Marigold", variant: "ทองเฉลิมสีเหลืองทอง", variantEn: "Thong Chaloem Golden Yellow" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ดาวเรือง", typeEn: "Marigold", variant: "ดุ๊กสีส้ม", variantEn: "Duke Orange" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ดาวเรือง", typeEn: "Marigold", variant: "มะนาวสีเหลืองอ่อน", variantEn: "Lime Light Yellow" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "บัวหลวง", typeEn: "Lotus", variant: "สัตตบุตย์สีขาว", variantEn: "Sattabuttra White" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "บัวหลวง", typeEn: "Lotus", variant: "สัตตบงกชสีชมพู", variantEn: "Sattabongkot Pink" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "บัวหลวง", typeEn: "Lotus", variant: "ประทุมสีชมพูสด", variantEn: "Prathum Bright Pink" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ดอกรัก", typeEn: "Crown Flower", variant: "ดอกรักสีขาว", variantEn: "White Crown Flower" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ดอกรัก", typeEn: "Crown Flower", variant: "ดอกรักสีม่วง", variantEn: "Purple Crown Flower" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "มะลิ", typeEn: "Jasmine", variant: "มะลิลาสีขาว", variantEn: "Mali La White" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "มะลิ", typeEn: "Jasmine", variant: "มะลิซ้อนสีขาว", variantEn: "Mali Son Double White" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ซ่อนกลิ่นไทย", typeEn: "Tuberose", variant: "ซ่อนกลิ่นดอกซ้อนสีขาว", variantEn: "Double White Tuberose" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ซ่อนกลิ่นไทย", typeEn: "Tuberose", variant: "ซ่อนกลิ่นดอกลาสีขาว", variantEn: "Single White Tuberose" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "พุด", typeEn: "Gardenia", variant: "ดอกพุดตูมสีขาว", variantEn: "Gardenia Bud White" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "ยูคาลิปตัส", typeEn: "Eucalyptus", variant: "ซิลเวอร์ดอลลาร์สีเขียวเงินใบกลม", variantEn: "Silver Dollar Eucalyptus" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "ยูคาลิปตัส", typeEn: "Eucalyptus", variant: "พาร์วิโฟเลียสีเขียวเข้มใบรี", variantEn: "Parvifolia Eucalyptus" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "เฟิร์น", typeEn: "Fern", variant: "ใบมะขามสีเขียวสด", variantEn: "Leatherleaf Fern" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "เฟิร์น", typeEn: "Fern", variant: "เฟิร์นนาคราชสีเขียวเข้ม", variantEn: "Davallia Fern" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "เฟิร์น", typeEn: "Fern", variant: "หนังขนนกสีเขียวโปร่ง", variantEn: "Asparagus Fern" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "เล็บครุฑ", typeEn: "Aralia", variant: "เล็บครุฑกระจกสีเขียวเข้ม", variantEn: "Geranium Aralia" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "เล็บครุฑ", typeEn: "Aralia", variant: "เล็บครุฑผักชีสีเขียวฝอย", variantEn: "Ming Aralia" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "หมากผู้หมากเมีย", typeEn: "Cordyline", variant: "ทับทิมสีแดงเข้ม", variantEn: "Ruby Cordyline" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "หมากผู้หมากเมีย", typeEn: "Cordyline", variant: "เขียวลายทางสีเขียวสลับขาว", variantEn: "Variegated Green Cordyline" },
];

/** Distinct flower types (Type_TH), in master-list order. */
export const FLOWER_TYPES: string[] = Array.from(new Set(FLOWERS.map((f) => f.type)));

/** Varieties belonging to one type — powers the cascading Type → Variety suggestion. */
export function variantsForType(type: string): string[] {
  const t = (type ?? "").trim();
  if (!t) return Array.from(new Set(FLOWERS.map((f) => f.variant)));
  return FLOWERS.filter((f) => f.type === t).map((f) => f.variant);
}

/** All variety names (used when no type is chosen yet). */
export const FLOWER_VARIANTS: string[] = Array.from(new Set(FLOWERS.map((f) => f.variant)));

export type ProductCategory = "flower" | "fruit" | "vegetable";
export const PRODUCT_CATEGORIES: { key: ProductCategory; label: string; unitDefault: "stem" | "kg" }[] = [
  { key: "flower", label: "ดอกไม้", unitDefault: "stem" },
  { key: "fruit", label: "ผลไม้", unitDefault: "kg" },
  { key: "vegetable", label: "ผัก", unitDefault: "kg" },
];
export const CATEGORY_LABEL: Record<ProductCategory, string> = { flower: "ดอกไม้", fruit: "ผลไม้", vegetable: "ผัก" };

export interface ProduceEntry extends FlowerEntry { productCategory: ProductCategory }

/** 200 fruit + vegetable varieties across 75 types — produce_master.xlsx */
export const PRODUCE: ProduceEntry[] = [
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ทุเรียน", typeEn: "Durian", variant: "หมอนทอง", variantEn: "Monthong" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ทุเรียน", typeEn: "Durian", variant: "ชะนี", variantEn: "Chanee" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ทุเรียน", typeEn: "Durian", variant: "ก้านยาว", variantEn: "Kan Yao" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ทุเรียน", typeEn: "Durian", variant: "พวงมณี", variantEn: "Puang Manee" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ทุเรียน", typeEn: "Durian", variant: "นกกระจิบ", variantEn: "Nok Krajib" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ทุเรียน", typeEn: "Durian", variant: "มูซังคิง", variantEn: "Musang King" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ทุเรียน", typeEn: "Durian", variant: "โอวฉี่ (หนามดำ)", variantEn: "Black Thorn (Ochee)" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ทุเรียน", typeEn: "Durian", variant: "นวลทองจันทร์", variantEn: "Nual Thong Chan" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ทุเรียน", typeEn: "Durian", variant: "หลงหลินลับแล", variantEn: "Long-Lin Laplae" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะม่วง", typeEn: "Mango", variant: "น้ำดอกไม้สีทอง", variantEn: "Nam Dok Mai Si Thong (Export)" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะม่วง", typeEn: "Mango", variant: "น้ำดอกไม้เบอร์ 4", variantEn: "Nam Dok Mai No. 4" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะม่วง", typeEn: "Mango", variant: "เขียวเสวย", variantEn: "Khieo Sa-woei" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะม่วง", typeEn: "Mango", variant: "มหาชนก", variantEn: "Mahachanok" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะม่วง", typeEn: "Mango", variant: "ฟ้าลั่น", variantEn: "Fa Lan" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะม่วง", typeEn: "Mango", variant: "โชคอนันต์", variantEn: "Chok Anan" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะม่วง", typeEn: "Mango", variant: "อกหมาก / อกฮ่องเต้", variantEn: "Ok Rong" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะม่วง", typeEn: "Mango", variant: "เขียวใหญ่", variantEn: "Khieo Yai" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะม่วง", typeEn: "Mango", variant: "แรด", variantEn: "Raet" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มังคุด", typeEn: "Mangosteen", variant: "ผิวมันเกรดส่งออก", variantEn: "Export Grade Smooth Skin" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มังคุด", typeEn: "Mangosteen", variant: "ผิวลาย / ผิวสายเลือด", variantEn: "Rough Skin / Blood Skin" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มังคุด", typeEn: "Mangosteen", variant: "ดำ (สุกเต็มที่)", variantEn: "Dark Purple / Fully Ripe" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "กล้วย", typeEn: "Banana", variant: "หอมทอง (ส่งออก)", variantEn: "Golden Banana (Export)" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "กล้วย", typeEn: "Banana", variant: "น้ำว้าปากช่อง 50", variantEn: "Nam Wa Pakchong 50" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "กล้วย", typeEn: "Banana", variant: "ไข่กำแพงเพชร", variantEn: "Kai Kamphaeng Phet" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "กล้วย", typeEn: "Banana", variant: "หักมุก", variantEn: "Hak Mook" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "กล้วย", typeEn: "Banana", variant: "เล็บมือนาง", variantEn: "Leb Mue Nang" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "สับปะรด", typeEn: "Pineapple", variant: "ภูแล", variantEn: "Phu Lae" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "สับปะรด", typeEn: "Pineapple", variant: "ศรีราชา / ปัตตาเวีย", variantEn: "Pattavia" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "สับปะรด", typeEn: "Pineapple", variant: "ห้วยมุ่น", variantEn: "Huai Mun" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "สับปะรด", typeEn: "Pineapple", variant: "นางแล", variantEn: "Nang Lae" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "สับปะรด", typeEn: "Pineapple", variant: "ตราดสีทอง", variantEn: "Trat Si Thong" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะพร้าว", typeEn: "Coconut", variant: "น้ำหอมบ้านแพ้ว", variantEn: "Ban Phaeo Aromatic Coconut" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะพร้าว", typeEn: "Coconut", variant: "มะพร้าวกะทิ", variantEn: "Macapuno Coconut" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะพร้าว", typeEn: "Coconut", variant: "มะพร้าวแกง", variantEn: "Seed Coconut" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "เงาะ", typeEn: "Rambutan", variant: "โรงเรียน", variantEn: "Rong Rien" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "เงาะ", typeEn: "Rambutan", variant: "สีชมพู", variantEn: "See Chompoo" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ลองกอง", typeEn: "Longkong / Langsat", variant: "ลองกองตันหยงมัส", variantEn: "Longkong Tanyongmas" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ลางสาด", typeEn: "Longkong / Langsat", variant: "ลางสาด", variantEn: "Langsat" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ลิ้นจี่", typeEn: "Lychee", variant: "จักรพรรดิ", variantEn: "Chakapat" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ลิ้นจี่", typeEn: "Lychee", variant: "สนมยิ้ม (ฮงฮ้วย)", variantEn: "Hong Huai" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ลิ้นจี่", typeEn: "Lychee", variant: "ค่อมลำปาง", variantEn: "Khom Lampang" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ลำไย", typeEn: "Longan", variant: "อีดอ", variantEn: "Edor (Export Grade)" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ลำไย", typeEn: "Longan", variant: "สีชมพู", variantEn: "Si Chomphu" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "ลำไย", typeEn: "Longan", variant: "เพชรสาคร", variantEn: "Phet Sakhon" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะละกอ", typeEn: "Papaya", variant: "ฮอลแลนด์ / ปลักไม้ลาย", variantEn: "Holland" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะละกอ", typeEn: "Papaya", variant: "แขกดำ", variantEn: "Khaek Dam" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "มะละกอ", typeEn: "Papaya", variant: "แขกนวล", variantEn: "Khaek Nual (Green Papaya)" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "แก้วมังกร", typeEn: "Dragon Fruit", variant: "เนื้อขาวเปลือกแดง", variantEn: "White Flesh Red Skin" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "แก้วมังกร", typeEn: "Dragon Fruit", variant: "เนื้อแดงเปลือกแดง (พันธุ์ทายวัน)", variantEn: "Red Flesh Red Skin" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "แก้วมังกร", typeEn: "Dragon Fruit", variant: "เปลือกเหลือง (อิสราเอล/เอกวาดอร์)", variantEn: "Yellow Dragon Fruit" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "เสาวรส", typeEn: "Passion Fruit", variant: "ไทนุง (สีม่วง)", variantEn: "Tainung Purple" },
  { productCategory: "fruit", category: "ผลไม้เขตร้อน", categoryEn: "Tropical Fruits", type: "เสาวรส", typeEn: "Passion Fruit", variant: "พันธุ์หม่านเทียนซิง (สีส้มหวาน)", variantEn: "Sweet Yellow Passion Fruit" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ส้ม", typeEn: "Orange", variant: "สายน้ำผึ้ง", variantEn: "Sai Nam Phueng" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ส้ม", typeEn: "Orange", variant: "โชกุน", variantEn: "Shogun" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ส้ม", typeEn: "Orange", variant: "เขียวหวานดำเนิน", variantEn: "Damnoen Khieo Wan" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ส้ม", typeEn: "Orange", variant: "ส้มตรุษจีน / ส้มไต้หวัน", variantEn: "Mandarins / Tangerines" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ส้มโอ", typeEn: "Pomelo", variant: "ทับทิมสยาม", variantEn: "Tubtim Siam" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ส้มโอ", typeEn: "Pomelo", variant: "ขาวใหญ่", variantEn: "Khao Yai" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ส้มโอ", typeEn: "Pomelo", variant: "ทองดี", variantEn: "Thong Dee" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ส้มโอ", typeEn: "Pomelo", variant: "ขาวแตงกวา", variantEn: "Khao Taengkwa" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ส้มโอ", typeEn: "Pomelo", variant: "ขาวน้ำพริก", variantEn: "Khao Nam Phrik" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "องุ่น", typeEn: "Grape", variant: "ไชน์มัสแคท", variantEn: "Shine Muscat" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "องุ่น", typeEn: "Grape", variant: "ไบโคนูร์ (ไร้เมล็ดสีดำ)", variantEn: "Baikonur Black Seedless" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "องุ่น", typeEn: "Grape", variant: "บิวตี้ซีดเลส", variantEn: "Beauty Seedless" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "องุ่น", typeEn: "Grape", variant: "แบล็คโอปอล", variantEn: "Black Opal" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "องุ่น", typeEn: "Grape", variant: "คริมสันซีดเลส (สีแดงไร้เมล็ด)", variantEn: "Crimson Seedless Red" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ฝรั่ง", typeEn: "Guava", variant: "กิมจู", variantEn: "Kimju" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ฝรั่ง", typeEn: "Guava", variant: "หงเป่าสือ (ไส้แดง)", variantEn: "Hong Bao Shi Red Flesh" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ฝรั่ง", typeEn: "Guava", variant: "เฟิ่นหงหมี่", variantEn: "Fen Hong Mi" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "ฝรั่ง", typeEn: "Guava", variant: "กลมสาลี่", variantEn: "Klom Sali" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "พุทรา", typeEn: "Jujube", variant: "นมสด", variantEn: "Milk Jujube" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "พุทรา", typeEn: "Jujube", variant: "สามรส", variantEn: "Sam Rot Jujube" },
  { productCategory: "fruit", category: "ผลไม้กึ่งเมืองหนาว/เขตอบอุ่น", categoryEn: "Subtropical Fruits", type: "พุทรา", typeEn: "Jujube", variant: "แอปเปิล", variantEn: "Apple Jujube" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "สตรอว์เบอร์รี", typeEn: "Strawberry", variant: "พระราชทาน 80", variantEn: "Royal 80" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "สตรอว์เบอร์รี", typeEn: "Strawberry", variant: "อะกิฮิเมะ", variantEn: "Akihime" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "สตรอว์เบอร์รี", typeEn: "Strawberry", variant: "พระราชทาน 88", variantEn: "Royal 88" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "แอปเปิล", typeEn: "Apple", variant: "ฟูจิ", variantEn: "Fuji" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "แอปเปิล", typeEn: "Apple", variant: "กาลา", variantEn: "Gala" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "แอปเปิล", typeEn: "Apple", variant: "เอนวี่", variantEn: "Envy" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "พลับ", typeEn: "Persimmon", variant: "พลับกรอบ", variantEn: "Crunchy Persimmon" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "พลับ", typeEn: "Persimmon", variant: "พลับนิ่ม / พลับหวาน", variantEn: "Sweet Soft Persimmon" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "พีช / ท้อ", typeEn: "Peach", variant: "พีชโครงการหลวง", variantEn: "Royal Project Peach" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "กีวี่", typeEn: "Kiwi", variant: "กีวี่สีเขียว", variantEn: "Green Kiwi" },
  { productCategory: "fruit", category: "ผลไม้เมืองหนาว", categoryEn: "Temperate Fruits", type: "กีวี่", typeEn: "Kiwi", variant: "กีวี่สีทอง", variantEn: "Gold Kiwi" },
  { productCategory: "fruit", category: "แตงและพืชตระกูลแตง", categoryEn: "Melons", type: "แตงโม", typeEn: "Watermelon", variant: "จินตหรา (เนื้อแดง)", variantEn: "Jintara Red Flesh" },
  { productCategory: "fruit", category: "แตงและพืชตระกูลแตง", categoryEn: "Melons", type: "แตงโม", typeEn: "Watermelon", variant: "ซอนย่า", variantEn: "Sonya" },
  { productCategory: "fruit", category: "แตงและพืชตระกูลแตง", categoryEn: "Melons", type: "แตงโม", typeEn: "Watermelon", variant: "กินรี (ไร้เมล็ด)", variantEn: "Kinnaree Seedless" },
  { productCategory: "fruit", category: "แตงและพืชตระกูลแตง", categoryEn: "Melons", type: "แตงโม", typeEn: "Watermelon", variant: "ตลับทอง / ไดมอนด์ (เนื้อเหลือง)", variantEn: "Yellow Flesh Watermelon" },
  { productCategory: "fruit", category: "แตงและพืชตระกูลแตง", categoryEn: "Melons", type: "เมลอน", typeEn: "Melon", variant: "คิโมจิ (เนื้อส้ม)", variantEn: "Kimochi Orange Flesh" },
  { productCategory: "fruit", category: "แตงและพืชตระกูลแตง", categoryEn: "Melons", type: "เมลอน", typeEn: "Melon", variant: "กรีนเน็ต (เนื้อเขียว)", variantEn: "Green Net" },
  { productCategory: "fruit", category: "แตงและพืชตระกูลแตง", categoryEn: "Melons", type: "เมลอน", typeEn: "Melon", variant: "ฮอกไกโด (เนื้อส้ม)", variantEn: "Hokkaido Orange Melon" },
  { productCategory: "fruit", category: "แตงและพืชตระกูลแตง", categoryEn: "Melons", type: "แคนตาลูป", typeEn: "Cantaloupe", variant: "ซันเลดี้", variantEn: "Sun Lady Cantaloupe" },
  { productCategory: "fruit", category: "แตงและพืชตระกูลแตง", categoryEn: "Melons", type: "แคนตาลูป", typeEn: "Cantaloupe", variant: "ทอแสง", variantEn: "Tor Saeng Cantaloupe" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริก", typeEn: "Chili", variant: "พริกจินดาแดง", variantEn: "Red Chinda Chili" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริก", typeEn: "Chili", variant: "พริกจินดาเขียว", variantEn: "Green Chinda Chili" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริก", typeEn: "Chili", variant: "พริกขี้หนูสวน", variantEn: "Bird's Eye Chili" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริก", typeEn: "Chili", variant: "พริกชี้ฟ้าแดง", variantEn: "Red Spur Chili" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริก", typeEn: "Chili", variant: "พริกชี้ฟ้าเขียว", variantEn: "Green Spur Chili" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริก", typeEn: "Chili", variant: "พริกหนุ่มเขียว", variantEn: "Northern Green Chili" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริก", typeEn: "Chili", variant: "พริกหนุ่มขาว", variantEn: "Northern Pale Green Chili" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริก", typeEn: "Chili", variant: "พริกซูเปอร์ฮอท", variantEn: "Super Hot Chili" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริกหวาน", typeEn: "Bell Pepper", variant: "พริกหวานสีแดง", variantEn: "Red Bell Pepper" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริกหวาน", typeEn: "Bell Pepper", variant: "พริกหวานสีเหลือง", variantEn: "Yellow Bell Pepper" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "พริกหวาน", typeEn: "Bell Pepper", variant: "พริกหวานสีเขียว", variantEn: "Green Bell Pepper" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะเขือเทศ", typeEn: "Tomato", variant: "ทวิสเกรซ / มะเขือเทศผลใหญ่", variantEn: "Large Commercial Tomato" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะเขือเทศ", typeEn: "Tomato", variant: "เชอร์รี่แดง (ทับทิมสยาม)", variantEn: "Red Cherry Tomato" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะเขือเทศ", typeEn: "Tomato", variant: "เชอร์รี่เหลือง / ส้ม (โซลาริโน)", variantEn: "Sweet Yellow Cherry Tomato" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะเขือเทศ", typeEn: "Tomato", variant: "มะเขือเทศทอด / มะเขือเทศส้มตำ", variantEn: "Cooking Tomato" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะเขือเทศ", typeEn: "Tomato", variant: "มะเขือเทศเนื้อ", variantEn: "Beefsteak Tomato" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "แตงกวา", typeEn: "Cucumber", variant: "แตงร้าน", variantEn: "Large Cucumber" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "แตงกวา", typeEn: "Cucumber", variant: "แตงกวาขาว / แตงกวาทั่วไป", variantEn: "Standard White Cucumber" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "แตงกวา", typeEn: "Cucumber", variant: "แตงกวาญี่ปุ่น", variantEn: "Japanese Cucumber" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "แตงกวา", typeEn: "Cucumber", variant: "แตงกวาเบบี้", variantEn: "Baby Cucumber" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักกาดหอม / สลัด", typeEn: "Lettuce", variant: "กรีนโอ๊ค", variantEn: "Green Oak Lettuce" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักกาดหอม / สลัด", typeEn: "Lettuce", variant: "เรดโอ๊ค", variantEn: "Red Oak Lettuce" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักกาดหอม / สลัด", typeEn: "Lettuce", variant: "คอส / โรเมน", variantEn: "Cos / Romaine Lettuce" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักกาดหอม / สลัด", typeEn: "Lettuce", variant: "บัตเตอร์เฮด", variantEn: "Butterhead Lettuce" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักกาดหอม / สลัด", typeEn: "Lettuce", variant: "ฟิลเลย์ ไอซ์เบิร์ก", variantEn: "Frillice Iceberg" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักกาดหอม / สลัด", typeEn: "Lettuce", variant: "กะหล่ำแก้ว / ไอซ์เบิร์ก", variantEn: "Crisphead / Iceberg Lettuce" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "คะน้า", typeEn: "Chinese Kale", variant: "คะน้ายอด", variantEn: "Tip Kale" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "คะน้า", typeEn: "Chinese Kale", variant: "คะน้าเห็ดหอม / คะน้าฮ่องกง", variantEn: "Hong Kong Kale / Shiitake Kale" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "คะน้า", typeEn: "Chinese Kale", variant: "เบบี้คะน้า", variantEn: "Baby Kale" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักบุ้ง", typeEn: "Morning Glory", variant: "ผักบุ้งจีน", variantEn: "Chinese Water Spinach" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักบุ้ง", typeEn: "Morning Glory", variant: "ผักบุ้งไทย / ผักบุ้งแก้ว", variantEn: "Thai Water Spinach" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักบุ้ง", typeEn: "Morning Glory", variant: "ผักบุ้งนา", variantEn: "Wild Water Spinach" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "กวางตุ้ง", typeEn: "Bok Choy / Choy Sum", variant: "กวางตุ้งไต้หวัน / เบบี้โบกฉ่อย", variantEn: "Taiwan Bok Choy" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "กวางตุ้ง", typeEn: "Bok Choy / Choy Sum", variant: "กวางตุ้งดอก", variantEn: "Flowering Choy Sum" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "กวางตุ้ง", typeEn: "Bok Choy / Choy Sum", variant: "กวางตุ้งใบ", variantEn: "Leaf Choy Sum" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "กะหล่ำปลี", typeEn: "Cabbage", variant: "กะหล่ำปลีเขียว", variantEn: "Green Cabbage" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "กะหล่ำปลี", typeEn: "Cabbage", variant: "กะหล่ำปลีม่วง", variantEn: "Red / Purple Cabbage" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "กะหล่ำปลี", typeEn: "Cabbage", variant: "กะหล่ำหัวหัวใจ", variantEn: "Heart Cabbage" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักกาดขาว", typeEn: "Chinese Cabbage", variant: "ผักกาดขาวปลี", variantEn: "Napa / Pekinensis Cabbage" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักกาดขาว", typeEn: "Chinese Cabbage", variant: "ผักกาดขาวปลีเข้าเข้ากลม", variantEn: "Round Chinese Cabbage" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักชี", typeEn: "Coriander", variant: "ผักชีไทย", variantEn: "Thai Coriander" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักชี", typeEn: "Coriander", variant: "ผักชีฝรั่ง / หอมเป", variantEn: "Sawtooth Coriander" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ผักชี", typeEn: "Coriander", variant: "ผักชีล้อม / ดิลล์", variantEn: "Dill / Fennel" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ขึ้นฉ่าย", typeEn: "Celery", variant: "ขึ้นฉ่ายจีน", variantEn: "Chinese Celery" },
  { productCategory: "vegetable", category: "ผักใบ", categoryEn: "Leafy Vegetables", type: "ขึ้นฉ่าย", typeEn: "Celery", variant: "ขึ้นฉ่ายฝรั่ง / เซเลอรี", variantEn: "Western Celery" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "ถั่วฝักยาว", typeEn: "Yardlong Bean", variant: "ถั่วฝักยาวเนื้อ / ไร้แป้ง", variantEn: "Dark Green Yardlong Bean" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "ถั่วฝักยาว", typeEn: "Yardlong Bean", variant: "ถั่วฝักยาวสีขาว / เขียวอ่อน", variantEn: "Pale Green Yardlong Bean" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "ถั่วพู", typeEn: "Winged Bean", variant: "ถั่วพูเขียว", variantEn: "Green Winged Bean" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "ถั่วลันเตา", typeEn: "Snow Pea / Sugar Snap", variant: "ถั่วลันเตากินฝัก", variantEn: "Snow Pea" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "ถั่วลันเตา", typeEn: "Snow Pea / Sugar Snap", variant: "ถั่วหวาน", variantEn: "Sugar Snap Pea" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะเขือ", typeEn: "Eggplant", variant: "มะเขือเจ้าพระยา", variantEn: "Chao Phraya Eggplant" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะเขือ", typeEn: "Eggplant", variant: "มะเขือยาวเขียว", variantEn: "Green Long Eggplant" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะเขือ", typeEn: "Eggplant", variant: "มะเขือยาวม่วง", variantEn: "Purple Long Eggplant" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะเขือ", typeEn: "Eggplant", variant: "มะเขือพวง", variantEn: "Turkey Berry" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะเขือ", typeEn: "Eggplant", variant: "มะเขือเปรี้ยว / มะเขือส้ม", variantEn: "Thai Sour Eggplant" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "ฟักทอง", typeEn: "Pumpkin", variant: "ศรีเมือง / ฟักทองไทย", variantEn: "Thai Kabocha Pumpkin" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "ฟักทอง", typeEn: "Pumpkin", variant: "บัตเตอร์นัท", variantEn: "Butternut Squash" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "ฟักทอง", typeEn: "Pumpkin", variant: "ฟักทองญี่ปุ่น", variantEn: "Japanese Pumpkin" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "บวบ", typeEn: "Gourd", variant: "บวบเหลี่ยม", variantEn: "Angled Luffa" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "บวบ", typeEn: "Gourd", variant: "บวบหอม", variantEn: "Smooth Luffa" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "บวบ", typeEn: "Gourd", variant: "บวบงู", variantEn: "Snake Gourd" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะระ", typeEn: "Bitter Gourd", variant: "มะระจีน", variantEn: "Chinese Bitter Gourd" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "มะระ", typeEn: "Bitter Gourd", variant: "มะระขี้นก", variantEn: "Small Bitter Gourd" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "ฟักเขียว", typeEn: "Winter Melon", variant: "ฟักเขียวผลใหญ่", variantEn: "Large Winter Melon" },
  { productCategory: "vegetable", category: "ผักผลและผักฝัก", categoryEn: "Fruit & Pod Vegetables", type: "แฟง", typeEn: "Winter Melon", variant: "แฟงหอม / แฟงเล็ก", variantEn: "Small Wax Gourd" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "หอมแดง", typeEn: "Shallot", variant: "หอมแดงศรีสะเกษ", variantEn: "Sisaket Shallot" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "หอมแดง", typeEn: "Shallot", variant: "หอมแดงแกะกลีบ", variantEn: "Peeled Shallot" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "หอมหัวใหญ่", typeEn: "Onion", variant: "หอมหัวใหญ่สีเหลืองทั่วไป", variantEn: "Yellow Onion" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "หอมหัวใหญ่", typeEn: "Onion", variant: "หอมหัวใหญ่สีแดง / ม่วง", variantEn: "Red / Purple Onion" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "กระเทียม", typeEn: "Garlic", variant: "กระเทียมไทยมัดจุก", variantEn: "Thai Small Garlic" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "กระเทียม", typeEn: "Garlic", variant: "กระเทียมจีน", variantEn: "Chinese Large Garlic" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "กระเทียม", typeEn: "Garlic", variant: "กระเทียมโทน", variantEn: "Single Clove Garlic" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "ขิง", typeEn: "Ginger", variant: "ขิงแก่", variantEn: "Mature Ginger" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "ขิง", typeEn: "Ginger", variant: "ขิงอ่อน", variantEn: "Young Ginger" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "ข่า", typeEn: "Galangal", variant: "ข่าตาแดง", variantEn: "Red Eye Galangal" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "ข่า", typeEn: "Galangal", variant: "ข่าหยวก / ข่าขาว", variantEn: "White Galangal" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "ตะไคร้", typeEn: "Lemongrass", variant: "ตะไคร้หยวก", variantEn: "Commercial Lemongrass" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "กะเพรา", typeEn: "Basil", variant: "กะเพราแดง", variantEn: "Red Holy Basil" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "กะเพรา", typeEn: "Basil", variant: "กะเพราขาว", variantEn: "White Holy Basil" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "โหระพา", typeEn: "Basil", variant: "โหระพา", variantEn: "Sweet Basil" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "แมงลัก", typeEn: "Basil", variant: "แมงลัก", variantEn: "Lemon Basil" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "มะกรูด", typeEn: "Kaffir Lime", variant: "ใบมะกรูด", variantEn: "Kaffir Lime Leaves" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "มะนาว", typeEn: "Lime", variant: "มะนาวแป้นรำไพ", variantEn: "Pan Rampai Lime" },
  { productCategory: "vegetable", category: "พืชเครื่องเทศและสมุนไพร", categoryEn: "Herb & Spice Vegetables", type: "มะนาว", typeEn: "Lime", variant: "มะนาวไร้เมล็ด / ตาฮิติ", variantEn: "Seedless Tahiti Lime" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "แครอท", typeEn: "Carrot", variant: "แครอทส้มทั่วไป", variantEn: "Standard Orange Carrot" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "แครอท", typeEn: "Carrot", variant: "เบบี้แครอท", variantEn: "Baby Carrot" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "หัวไชเท้า", typeEn: "Radish", variant: "ไชเท้าขาว", variantEn: "White Radish" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "หัวไชเท้า", typeEn: "Radish", variant: "เรดิชสีแดง", variantEn: "Red Globe Radish" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "มันฝรั่ง", typeEn: "Potato", variant: "มันฝรั่งสดบริโภค", variantEn: "Table Potato" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "มันฝรั่ง", typeEn: "Potato", variant: "มันฝรั่งแปรรูป", variantEn: "Processed Chip Potato" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "มันเทศ", typeEn: "Sweet Potato", variant: "มันเทศสีส้มโอกินาวา", variantEn: "Okinawa Orange Sweet Potato" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "มันเทศ", typeEn: "Sweet Potato", variant: "มันม่วงญี่ปุ่น", variantEn: "Japanese Purple Sweet Potato" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "มันเทศ", typeEn: "Sweet Potato", variant: "มันไข่", variantEn: "Yellow Sweet Potato" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "เผือก", typeEn: "Taro", variant: "เผือกหอมเชียงใหม่", variantEn: "Fragrant Taro" },
  { productCategory: "vegetable", category: "ผักหัวและราก", categoryEn: "Root & Tuber Vegetables", type: "มันแกว", typeEn: "Jicama", variant: "มันแกวบรบือ", variantEn: "Yam Bean" },
  { productCategory: "vegetable", category: "ผักดอก", categoryEn: "Flower Vegetables", type: "บรอกโคลี", typeEn: "Broccoli", variant: "บรอกโคลีเขียว", variantEn: "Green Broccoli" },
  { productCategory: "vegetable", category: "ผักดอก", categoryEn: "Flower Vegetables", type: "กะหล่ำดอก", typeEn: "Cauliflower", variant: "กะหล่ำดอกขาว", variantEn: "White Cauliflower" },
  { productCategory: "vegetable", category: "ผักดอก", categoryEn: "Flower Vegetables", type: "กะหล่ำดอก", typeEn: "Cauliflower", variant: "กะหล่ำดอกเจดีย์", variantEn: "Romanesco Broccoli" },
  { productCategory: "vegetable", category: "ผักดอก", categoryEn: "Flower Vegetables", type: "ดอกกุยช่าย", typeEn: "Chive Flower", variant: "ดอกกุยช่ายสด", variantEn: "Fresh Chive Flower" },
  { productCategory: "vegetable", category: "ผักดอก", categoryEn: "Flower Vegetables", type: "ดอกแค", typeEn: "Sesbania Flower", variant: "ดอกแคขาว", variantEn: "White Sesbania" },
  { productCategory: "vegetable", category: "ผักดอก", categoryEn: "Flower Vegetables", type: "ดอกขจร / สลิด", typeEn: "Cowslip Creeper", variant: "ดอกขจรสด", variantEn: "Fresh Cowslip Creeper" },
  { productCategory: "vegetable", category: "ผักใบพื้นบ้าน", categoryEn: "Local Leafy Vegetables", type: "ตำลึง", typeEn: "Ivy Gourd", variant: "ตำลึงยอดอ่อน", variantEn: "Ivy Gourd Shoots" },
  { productCategory: "vegetable", category: "ผักใบพื้นบ้าน", categoryEn: "Local Leafy Vegetables", type: "ชะอม", typeEn: "Cha-om", variant: "ชะอมยอดอ่อน", variantEn: "Fresh Cha-om Shoots" },
  { productCategory: "vegetable", category: "ผักใบพื้นบ้าน", categoryEn: "Local Leafy Vegetables", type: "ผักหวาน", typeEn: "Sweet Leaf", variant: "ผักหวานบ้าน", variantEn: "Bush Greens / Sweet Leaf" },
  { productCategory: "vegetable", category: "ผักใบพื้นบ้าน", categoryEn: "Local Leafy Vegetables", type: "ผักหวาน", typeEn: "Sweet Leaf", variant: "ผักหวานป่า", variantEn: "Wild Sweet Leaf" },
  { productCategory: "vegetable", category: "ผักใบพื้นบ้าน", categoryEn: "Local Leafy Vegetables", type: "ใบเหลียง", typeEn: "Liang Leaves", variant: "ใบเหลียงยอดอ่อน", variantEn: "Fresh Liang Leaves" },
  { productCategory: "vegetable", category: "ผักใบพื้นบ้าน", categoryEn: "Local Leafy Vegetables", type: "สะดาด / สะเดา", typeEn: "Neem", variant: "สะเดามัน / สะเดาทวาย", variantEn: "Bitter Neem Shoots" },
];

/** Every product (flowers + produce) with its top-level category — the 3-level master:
 *  ประเภทสินค้า (ดอกไม้/ผลไม้/ผัก) → ชนิด → พันธุ์ */
export const PRODUCTS: ProduceEntry[] = [
  ...FLOWERS.map((f) => ({ ...f, productCategory: "flower" as const })),
  ...PRODUCE,
];

/** Distinct types (ชนิด) of one product category, in master-list order. */
export function typesFor(category: ProductCategory): string[] {
  return Array.from(new Set(PRODUCTS.filter((p) => p.productCategory === category).map((p) => p.type)));
}

/** Varieties (พันธุ์) of one type within a category. */
export function variantsFor(category: ProductCategory, type: string): string[] {
  const t = (type ?? "").trim();
  return PRODUCTS.filter((p) => p.productCategory === category && (!t || p.type === t)).map((p) => p.variant);
}

/** Category of a known type name (ชนิด) — undefined for free-text "อื่นๆ". */
export function categoryOfType(type: string): ProductCategory | undefined {
  return PRODUCTS.find((p) => p.type === type)?.productCategory;
}

export interface ProduceProfile {
  type: string; category: ProductCategory;
  shelfLifeDays: number;            // อายุการเก็บรักษามาตรฐาน (วัน) ที่อุณหภูมิเหมาะสม
  storageMinC: number; storageMaxC: number; // อุณหภูมิเก็บรักษาที่เหมาะสม
  chillSensitive: boolean;          // ห้ามแช่เย็นต่ำกว่า storageMinC (ผลไม้เขตร้อนส่วนใหญ่)
  ripens: boolean;                  // สุกต่อหลังเก็บเกี่ยว (climacteric)
  note: string;
}

/** 75 postharvest profiles by type — produce_profile.csv (KLORA defaults, editable) */
export const PRODUCE_PROFILES: ProduceProfile[] = [
  { type: "ทุเรียน", category: "fruit", shelfLifeDays: 7, storageMinC: 13, storageMaxC: 15, chillSensitive: true, ripens: true, note: "ห้ามเก็บต่ำกว่า 13°C" },
  { type: "มะม่วง", category: "fruit", shelfLifeDays: 14, storageMinC: 10, storageMaxC: 13, chillSensitive: true, ripens: true, note: "ต่ำกว่า 10°C ผิวคล้ำ" },
  { type: "มังคุด", category: "fruit", shelfLifeDays: 21, storageMinC: 13, storageMaxC: 13, chillSensitive: true, ripens: false, note: "เปลือกแข็งถ้าเย็นเกิน" },
  { type: "กล้วย", category: "fruit", shelfLifeDays: 10, storageMinC: 13, storageMaxC: 14, chillSensitive: true, ripens: true, note: "ต่ำกว่า 13°C ผิวดำ" },
  { type: "สับปะรด", category: "fruit", shelfLifeDays: 21, storageMinC: 7, storageMaxC: 13, chillSensitive: true, ripens: false, note: "" },
  { type: "มะพร้าว", category: "fruit", shelfLifeDays: 21, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "เงาะ", category: "fruit", shelfLifeDays: 10, storageMinC: 10, storageMaxC: 12, chillSensitive: true, ripens: false, note: "ขนดำเร็วถ้าแห้ง" },
  { type: "ลองกอง", category: "fruit", shelfLifeDays: 10, storageMinC: 12, storageMaxC: 15, chillSensitive: true, ripens: false, note: "" },
  { type: "ลางสาด", category: "fruit", shelfLifeDays: 7, storageMinC: 12, storageMaxC: 15, chillSensitive: true, ripens: false, note: "" },
  { type: "ลิ้นจี่", category: "fruit", shelfLifeDays: 14, storageMinC: 2, storageMaxC: 5, chillSensitive: false, ripens: false, note: "" },
  { type: "ลำไย", category: "fruit", shelfLifeDays: 21, storageMinC: 2, storageMaxC: 5, chillSensitive: false, ripens: false, note: "" },
  { type: "มะละกอ", category: "fruit", shelfLifeDays: 10, storageMinC: 10, storageMaxC: 13, chillSensitive: true, ripens: true, note: "" },
  { type: "แก้วมังกร", category: "fruit", shelfLifeDays: 21, storageMinC: 7, storageMaxC: 10, chillSensitive: true, ripens: false, note: "" },
  { type: "เสาวรส", category: "fruit", shelfLifeDays: 21, storageMinC: 7, storageMaxC: 10, chillSensitive: true, ripens: true, note: "" },
  { type: "ส้ม", category: "fruit", shelfLifeDays: 28, storageMinC: 5, storageMaxC: 8, chillSensitive: false, ripens: false, note: "" },
  { type: "ส้มโอ", category: "fruit", shelfLifeDays: 42, storageMinC: 8, storageMaxC: 10, chillSensitive: false, ripens: false, note: "" },
  { type: "องุ่น", category: "fruit", shelfLifeDays: 28, storageMinC: 0, storageMaxC: 1, chillSensitive: false, ripens: false, note: "" },
  { type: "ฝรั่ง", category: "fruit", shelfLifeDays: 14, storageMinC: 8, storageMaxC: 10, chillSensitive: true, ripens: true, note: "" },
  { type: "พุทรา", category: "fruit", shelfLifeDays: 14, storageMinC: 5, storageMaxC: 10, chillSensitive: false, ripens: false, note: "" },
  { type: "สตรอว์เบอร์รี", category: "fruit", shelfLifeDays: 5, storageMinC: 0, storageMaxC: 2, chillSensitive: false, ripens: false, note: "เน่าเร็ว" },
  { type: "แอปเปิล", category: "fruit", shelfLifeDays: 60, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "พลับ", category: "fruit", shelfLifeDays: 21, storageMinC: 0, storageMaxC: 2, chillSensitive: false, ripens: true, note: "" },
  { type: "พีช / ท้อ", category: "fruit", shelfLifeDays: 10, storageMinC: 0, storageMaxC: 2, chillSensitive: false, ripens: true, note: "" },
  { type: "กีวี่", category: "fruit", shelfLifeDays: 42, storageMinC: 0, storageMaxC: 1, chillSensitive: false, ripens: true, note: "" },
  { type: "แตงโม", category: "fruit", shelfLifeDays: 14, storageMinC: 10, storageMaxC: 15, chillSensitive: true, ripens: false, note: "" },
  { type: "เมลอน", category: "fruit", shelfLifeDays: 14, storageMinC: 7, storageMaxC: 10, chillSensitive: true, ripens: true, note: "" },
  { type: "แคนตาลูป", category: "fruit", shelfLifeDays: 14, storageMinC: 2, storageMaxC: 5, chillSensitive: false, ripens: true, note: "" },
  { type: "พริก", category: "vegetable", shelfLifeDays: 14, storageMinC: 7, storageMaxC: 10, chillSensitive: true, ripens: false, note: "" },
  { type: "พริกหวาน", category: "vegetable", shelfLifeDays: 14, storageMinC: 7, storageMaxC: 10, chillSensitive: true, ripens: false, note: "" },
  { type: "มะเขือเทศ", category: "vegetable", shelfLifeDays: 10, storageMinC: 10, storageMaxC: 13, chillSensitive: true, ripens: true, note: "ต่ำกว่า 10°C เนื้อฟ่าม" },
  { type: "แตงกวา", category: "vegetable", shelfLifeDays: 10, storageMinC: 10, storageMaxC: 12, chillSensitive: true, ripens: false, note: "" },
  { type: "ผักกาดหอม / สลัด", category: "vegetable", shelfLifeDays: 7, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "ผักใบสด" },
  { type: "คะน้า", category: "vegetable", shelfLifeDays: 7, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ผักบุ้ง", category: "vegetable", shelfLifeDays: 4, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "กวางตุ้ง", category: "vegetable", shelfLifeDays: 5, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "กะหล่ำปลี", category: "vegetable", shelfLifeDays: 30, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ผักกาดขาว", category: "vegetable", shelfLifeDays: 21, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ผักชี", category: "vegetable", shelfLifeDays: 5, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ขึ้นฉ่าย", category: "vegetable", shelfLifeDays: 14, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ถั่วฝักยาว", category: "vegetable", shelfLifeDays: 7, storageMinC: 7, storageMaxC: 10, chillSensitive: true, ripens: false, note: "" },
  { type: "ถั่วพู", category: "vegetable", shelfLifeDays: 5, storageMinC: 7, storageMaxC: 10, chillSensitive: true, ripens: false, note: "" },
  { type: "ถั่วลันเตา", category: "vegetable", shelfLifeDays: 7, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "มะเขือ", category: "vegetable", shelfLifeDays: 10, storageMinC: 10, storageMaxC: 12, chillSensitive: true, ripens: false, note: "" },
  { type: "ฟักทอง", category: "vegetable", shelfLifeDays: 60, storageMinC: 10, storageMaxC: 15, chillSensitive: true, ripens: false, note: "" },
  { type: "บวบ", category: "vegetable", shelfLifeDays: 7, storageMinC: 10, storageMaxC: 12, chillSensitive: true, ripens: false, note: "" },
  { type: "มะระ", category: "vegetable", shelfLifeDays: 10, storageMinC: 10, storageMaxC: 12, chillSensitive: true, ripens: false, note: "" },
  { type: "ฟักเขียว", category: "vegetable", shelfLifeDays: 60, storageMinC: 10, storageMaxC: 15, chillSensitive: true, ripens: false, note: "" },
  { type: "แฟง", category: "vegetable", shelfLifeDays: 30, storageMinC: 10, storageMaxC: 15, chillSensitive: true, ripens: false, note: "" },
  { type: "หอมแดง", category: "vegetable", shelfLifeDays: 90, storageMinC: 0, storageMaxC: 5, chillSensitive: false, ripens: false, note: "เก็บได้เป็นเดือน" },
  { type: "หอมหัวใหญ่", category: "vegetable", shelfLifeDays: 90, storageMinC: 0, storageMaxC: 5, chillSensitive: false, ripens: false, note: "" },
  { type: "กระเทียม", category: "vegetable", shelfLifeDays: 120, storageMinC: 0, storageMaxC: 5, chillSensitive: false, ripens: false, note: "" },
  { type: "ขิง", category: "vegetable", shelfLifeDays: 30, storageMinC: 12, storageMaxC: 14, chillSensitive: true, ripens: false, note: "" },
  { type: "ข่า", category: "vegetable", shelfLifeDays: 21, storageMinC: 12, storageMaxC: 14, chillSensitive: true, ripens: false, note: "" },
  { type: "ตะไคร้", category: "vegetable", shelfLifeDays: 14, storageMinC: 10, storageMaxC: 13, chillSensitive: true, ripens: false, note: "" },
  { type: "กะเพรา", category: "vegetable", shelfLifeDays: 5, storageMinC: 10, storageMaxC: 13, chillSensitive: true, ripens: false, note: "ใบดำถ้าเย็นเกิน" },
  { type: "โหระพา", category: "vegetable", shelfLifeDays: 5, storageMinC: 10, storageMaxC: 13, chillSensitive: true, ripens: false, note: "" },
  { type: "แมงลัก", category: "vegetable", shelfLifeDays: 4, storageMinC: 10, storageMaxC: 13, chillSensitive: true, ripens: false, note: "" },
  { type: "มะกรูด", category: "vegetable", shelfLifeDays: 14, storageMinC: 10, storageMaxC: 13, chillSensitive: true, ripens: false, note: "" },
  { type: "มะนาว", category: "vegetable", shelfLifeDays: 21, storageMinC: 8, storageMaxC: 10, chillSensitive: true, ripens: false, note: "" },
  { type: "แครอท", category: "vegetable", shelfLifeDays: 30, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "หัวไชเท้า", category: "vegetable", shelfLifeDays: 14, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "มันฝรั่ง", category: "vegetable", shelfLifeDays: 60, storageMinC: 7, storageMaxC: 10, chillSensitive: true, ripens: false, note: "ต่ำกว่า 7°C แป้งเปลี่ยนเป็นน้ำตาล" },
  { type: "มันเทศ", category: "vegetable", shelfLifeDays: 45, storageMinC: 13, storageMaxC: 15, chillSensitive: true, ripens: false, note: "" },
  { type: "เผือก", category: "vegetable", shelfLifeDays: 30, storageMinC: 10, storageMaxC: 13, chillSensitive: true, ripens: false, note: "" },
  { type: "มันแกว", category: "vegetable", shelfLifeDays: 21, storageMinC: 12, storageMaxC: 15, chillSensitive: true, ripens: false, note: "" },
  { type: "บรอกโคลี", category: "vegetable", shelfLifeDays: 7, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "กะหล่ำดอก", category: "vegetable", shelfLifeDays: 10, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ดอกกุยช่าย", category: "vegetable", shelfLifeDays: 5, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ดอกแค", category: "vegetable", shelfLifeDays: 3, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ดอกขจร / สลิด", category: "vegetable", shelfLifeDays: 3, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ตำลึง", category: "vegetable", shelfLifeDays: 4, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ชะอม", category: "vegetable", shelfLifeDays: 4, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ผักหวาน", category: "vegetable", shelfLifeDays: 4, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "ใบเหลียง", category: "vegetable", shelfLifeDays: 5, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
  { type: "สะดาด / สะเดา", category: "vegetable", shelfLifeDays: 4, storageMinC: 0, storageMaxC: 4, chillSensitive: false, ripens: false, note: "" },
];

/** Postharvest profile for a type; flowers and unknown types get a conservative default. */
export function profileFor(type: string | undefined, category: ProductCategory = "flower"): ProduceProfile {
  const hit = type ? PRODUCE_PROFILES.find((p) => p.type === type) : undefined;
  if (hit) return hit;
  if (category === "flower") return { type: type ?? "", category, shelfLifeDays: 7, storageMinC: 2, storageMaxC: 5, chillSensitive: false, ripens: false, note: "ดอกไม้ตัด — ยิ่งเย็นยิ่งสดนาน" };
  return { type: type ?? "", category, shelfLifeDays: 7, storageMinC: 5, storageMaxC: 10, chillSensitive: false, ripens: category === "fruit", note: "" };
}

export interface PackagingMaterial {
  category: string; material: string; materialEn: string;
  unit: string; efRange: string; efDefault: number;
  lifespan: string; standardWeight: string; note: string;
}

/** 14 materials — flower_shipping_packaging_ef_list */
export const PACKAGING_MATERIALS: PackagingMaterial[] = [
  { category: "บรรจุภัณฑ์หลัก (กล่อง/ภาชนะ)", material: "ตะกร้าพลาสติกขนส่ง (HDPE - Dutch bucket style)", materialEn: "Plastic Transport Basket (HDPE)", unit: "kg CO2e / kg วัสดุ", efRange: "1.8 - 2.5", efDefault: 2.5, lifespan: "50 - 100 รอบ", standardWeight: "1.20 - 1.80 kg / ใบ", note: "ใช้ซ้ำได้หลายรอบ นิยมใช้แช่น้ำส่งดอกไม้ก้านยาว เช่น กุหลาบ ลิลลี่" },
  { category: "บรรจุภัณฑ์หลัก (กล่อง/ภาชนะ)", material: "กล่องกระดาษลูกฟูก (เยื่อใหม่ Virgin)", materialEn: "Corrugated Box (Virgin Pulp)", unit: "kg CO2e / kg วัสดุ", efRange: "0.91 - 1.14", efDefault: 1.05, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.30 - 0.70 kg / กล่อง", note: "น้ำหนักขึ้นอยู่กับขนาดกล่องและความหนาของลอน" },
  { category: "บรรจุภัณฑ์หลัก (กล่อง/ภาชนะ)", material: "กล่องกระดาษลูกฟูก (เยื่อรีไซเคิล Recycled)", materialEn: "Corrugated Box (Recycled Pulp)", unit: "kg CO2e / kg วัสดุ", efRange: "0.73 - 0.82", efDefault: 0.82, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.30 - 0.70 kg / กล่อง", note: "เป็นมิตรต่อสิ่งแวดล้อมมากกว่า แต่ความแข็งแรงต่อความชื้นลดลงเล็กน้อย" },
  { category: "วัสดุห่อหุ้มและกันกระแทก", material: "แผ่นพลาสติกใส/ซองห่อช่อดอกไม้ (OPP / PE Film)", materialEn: "Clear Plastic Wrapping Sleeve (OPP / PE Film)", unit: "kg CO2e / kg วัสดุ", efRange: "2.0 - 3.5", efDefault: 2.5, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.005 - 0.015 kg / แผ่น", note: "ใช้ห่อช่อดอกไม้เพื่อความสวยงามและป้องกันกลีบดอกช้ำ" },
  { category: "วัสดุห่อหุ้มและกันกระแทก", material: "ถุงพลาสติกหูหิ้ว/ถุงคุมอุณหภูมิ (LDPE)", materialEn: "Plastic Bag (LDPE)", unit: "kg CO2e / kg วัสดุ", efRange: "2.0 - 3.0", efDefault: 2.2, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.010 - 0.040 kg / ใบ", note: "ใช้ใส่กำดอกไม้ขายส่ง หรือรองก้นตะกร้าเพื่อขังน้ำ" },
  { category: "วัสดุห่อหุ้มและกันกระแทก", material: "กระดาษคราฟท์ห่อช่อ / กระดาษรังผึ้งกันกระแทก", materialEn: "Kraft Wrapping Paper / Honeycomb Cushioning", unit: "kg CO2e / kg วัสดุ", efRange: "0.70 - 0.95", efDefault: 0.85, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.015 - 0.035 kg / แผ่น", note: "วัสดุทดแทนพลาสติกยอดนิยมสำหรับแบรนด์รักษ์โลก" },
  { category: "วัสดุห่อหุ้มและกันกระแทก", material: "กระดาษหนังสือพิมพ์ / กระดาษฉีกรองก้นกล่อง", materialEn: "Newsprint / Shredded Paper Filler", unit: "kg CO2e / kg วัสดุ", efRange: "0.50 - 0.73", efDefault: 0.65, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.050 - 0.150 kg / กล่อง", note: "ใช้ขยำรองก้นกล่องหรือห่อหุ้มกำดอกไม้เพื่อซับความชื้น" },
  { category: "วัสดุผูกยึดและปิดผนึก", material: "เทปกาวพลาสติกปิดกล่อง (OPP Tape)", materialEn: "Plastic Packaging Tape (OPP)", unit: "kg CO2e / เมตร", efRange: "0.01 - 0.03", efDefault: 0.02, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.002 - 0.005 kg / เมตร", note: "คำนวณตามความยาวที่ใช้จริงต่อกล่อง (เฉลี่ยกล่องละ 1-2 เมตร)" },
  { category: "วัสดุผูกยึดและปิดผนึก", material: "เทปกาวกระดาษคราฟท์ (Kraft Paper Tape)", materialEn: "Kraft Paper Packaging Tape", unit: "kg CO2e / เมตร", efRange: "0.005 - 0.015", efDefault: 0.01, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.002 - 0.004 kg / เมตร", note: "ย่อยสลายง่าย รีไซเคิลพร้อมกล่องลูกฟูกได้เลย" },
  { category: "วัสดุผูกยึดและปิดผนึก", material: "เชือกฟางพลาสติก (PP Straw Rope)", materialEn: "Plastic Straw Rope (PP)", unit: "kg CO2e / เมตร", efRange: "0.01 - 0.02", efDefault: 0.015, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.001 - 0.003 kg / เมตร", note: "นิยมใช้มัดกำดอกไม้สดและผูกกล่องขนส่งขนาดใหญ่" },
  { category: "วัสดุผูกยึดและปิดผนึก", material: "เชือกปอ / เชือกป่านธรรมชาติ (Jute Twine)", materialEn: "Natural Jute Twine", unit: "kg CO2e / เมตร", efRange: "0.002 - 0.006", efDefault: 0.004, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.001 - 0.002 kg / เมตร", note: "เชือกใยธรรมชาติ คาร์บอนต่ำมาก นิยมใช้ผูกช่อสไตล์มินิมอล" },
  { category: "วัสดุรักษาคุณภาพและความสด", material: "โอเอซิส / โฟมปักดอกไม้ (Floral Foam)", materialEn: "Floral Foam (Oasis)", unit: "kg CO2e / ก้อนมาตรฐาน", efRange: "0.15 - 0.35", efDefault: 0.25, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.040 - 0.050 kg / ก้อน", note: "เป็นไมโครพลาสติกที่ไม่ย่อยสลาย มีค่า EF สูงเมื่อเทียบกับน้ำหนักแห้ง" },
  { category: "วัสดุรักษาคุณภาพและความสด", material: "หลอดน้ำเลี้ยงก้านดอกไม้ (Water Tubes/Vials)", materialEn: "Plastic Flower Water Tubes/Vials", unit: "kg CO2e / ชิ้น", efRange: "0.015 - 0.030", efDefault: 0.022, lifespan: "1 รอบ (reuse ได้ถ้าเก็บคืน)", standardWeight: "0.003 - 0.006 kg / ชิ้น", note: "หลอดพลาสติกพร้อมฝายางสำหรับสวมโคนก้านเดี่ยวเพื่อขังน้ำเลี้ยง" },
  { category: "วัสดุรักษาคุณภาพและความสด", material: "เจลเก็บความเย็น / ไอซ์แพค", materialEn: "Cool Gel Pack / Ice Pack", unit: "kg CO2e / ชิ้น", efRange: "0.05 - 0.15", efDefault: 0.08, lifespan: "ใช้ซ้ำได้ (ระบบปิด)", standardWeight: "0.100 - 0.400 kg / ชิ้น", note: "ใช้ควบคุมอุณหภูมิในกล่องระหว่างขนส่งดอกไม้เมืองหนาว" },
];

export interface VehicleFuel {
  category: string; vehicle: string; vehicleEn: string;
  fuel: string; fuelEn: string;
  vehicleKey: string; fuelKey: string;
}

/** 23 vehicle x fuel pairs — vehicle_and_fuel_mapping_list.
 *  NOTE: KYN supplied the mapping/enum only — EF_tkm / EF_vkm values are NOT in the file
 *  and must be obtained from KYN or TGO before the transport formula can use them. */
export const VEHICLE_FUELS: VehicleFuel[] = [
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ขนาดเล็ก", vehicleEn: "Eco Car / Sedan", fuel: "แก๊สโซฮอล์ 91 / 95 (E10)", fuelEn: "Gasohol 91 / 95 (E10)", vehicleKey: "sedan", fuelKey: "E10" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ขนาดเล็ก", vehicleEn: "Eco Car / Sedan", fuel: "แก๊สโซฮอล์ E20", fuelEn: "Gasohol E20", vehicleKey: "sedan", fuelKey: "E20" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ขนาดเล็ก", vehicleEn: "Eco Car / Sedan", fuel: "แก๊สโซฮอล์ E85", fuelEn: "Gasohol E85", vehicleKey: "sedan", fuelKey: "E85" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ขนาดเล็ก", vehicleEn: "Eco Car / Sedan", fuel: "น้ำมันเบนซินไร้สารตะกั่ว", fuelEn: "Pure Gasoline", vehicleKey: "sedan", fuelKey: "gasoline" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์อเนกประสงค์", vehicleEn: "SUV / PPV", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "suv", fuelKey: "B7" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ไฟฟ้า (EV)", vehicleEn: "Battery EV", fuel: "ไฟฟ้า 100% (Battery EV)", fuelEn: "Electricity (EV)", vehicleKey: "ev_passenger", fuelKey: "EV" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ไฮบริด / ปลั๊กอินไฮบริด", vehicleEn: "HEV / PHEV", fuel: "แก๊สโซฮอล์ 91 / 95 (E10)", fuelEn: "Gasohol 91 / 95 (E10)", vehicleKey: "phev_hev", fuelKey: "E10" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถกระบะบรรทุก 4 ล้อ", vehicleEn: "Pick-up Truck", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "pickup", fuelKey: "B7" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถกระบะบรรทุก 4 ล้อ", vehicleEn: "Pick-up Truck", fuel: "ดีเซล B10", fuelEn: "Diesel B10", vehicleKey: "pickup", fuelKey: "B10" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถกระบะบรรทุก 4 ล้อ", vehicleEn: "Pick-up Truck", fuel: "ดีเซล B20", fuelEn: "Diesel B20", vehicleKey: "pickup", fuelKey: "B20" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถกระบะบรรทุก 4 ล้อ", vehicleEn: "Pick-up Truck", fuel: "CNG / NGV", fuelEn: "CNG / NGV", vehicleKey: "pickup", fuelKey: "CNG" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถกระบะบรรทุก 4 ล้อ", vehicleEn: "Pick-up Truck", fuel: "LPG", fuelEn: "LPG", vehicleKey: "pickup", fuelKey: "LPG" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถตู้ขนส่งพัสดุ", vehicleEn: "Cargo Van", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "van", fuelKey: "B7" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถอเนกประสงค์ขนาดเล็ก", vehicleEn: "Light Motor Vehicle (LMV)", fuel: "แก๊สโซฮอล์ 91 / 95 (E10)", fuelEn: "Gasohol 91 / 95 (E10)", vehicleKey: "lmv", fuelKey: "E10" },
  { category: "รถบรรทุกขนาดใหญ่", vehicle: "รถบรรทุก 6 ล้อ", vehicleEn: "6-wheeler Truck", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "6_wheeler", fuelKey: "B7" },
  { category: "รถบรรทุกขนาดใหญ่", vehicle: "รถบรรทุก 10 ล้อ", vehicleEn: "10-wheeler Truck", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "10_wheeler", fuelKey: "B7" },
  { category: "รถพ่วงและรถกึ่งพ่วง", vehicle: "รถลากพ่วง", vehicleEn: "Full Trailer", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "full_trailer", fuelKey: "B7" },
  { category: "รถพ่วงและรถกึ่งพ่วง", vehicle: "รถกึ่งพ่วง", vehicleEn: "Semi-Trailer", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "semi_trailer", fuelKey: "B7" },
  { category: "รถโดยสาร", vehicle: "รถโดยสารประจำทาง / รถทัวร์", vehicleEn: "Standard Bus", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "bus", fuelKey: "B7" },
  { category: "รถจักรยานยนต์", vehicle: "รถจักรยานยนต์ขนส่งพัสดุ", vehicleEn: "Delivery Motorcycle", fuel: "แก๊สโซฮอล์ 91 / 95 (E10)", fuelEn: "Gasohol 91 / 95 (E10)", vehicleKey: "motorcycle", fuelKey: "E10" },
  { category: "รถจักรยานยนต์", vehicle: "รถจักรยานยนต์ขนส่งพัสดุ", vehicleEn: "Delivery Motorcycle", fuel: "แก๊สโซฮอล์ E20", fuelEn: "Gasohol E20", vehicleKey: "motorcycle", fuelKey: "E20" },
  { category: "รถจักรยานยนต์", vehicle: "รถจักรยานยนต์ขนส่งพัสดุ", vehicleEn: "Delivery Motorcycle", fuel: "ไฟฟ้า 100% (Battery EV)", fuelEn: "Electricity (EV)", vehicleKey: "motorcycle_ev", fuelKey: "EV" },
  { category: "ระบบไฮบริด / สองเชื้อเพลิง", vehicle: "น้ำมัน สลับ ก๊าซ", vehicleEn: "Bi-Fuel (Gasoline + LPG/NGV)", fuel: "ระบบเชื้อเพลิงสองระบบ", fuelEn: "Bi-Fuel", vehicleKey: "bi_fuel", fuelKey: "bi_fuel" },
];
