// AUTO-GENERATED by scripts/gen-master-data.mjs — do not edit by hand.
// Source: data/master/*.csv (master reference data supplied by KYN, 24 Aug 2026).

export interface FlowerEntry {
  category: string; categoryEn: string;
  type: string; typeEn: string;
  variant: string; variantEn: string;
}

/** 85 varieties across 28 types — thailand_cut_flowers_list */
export const FLOWERS: FlowerEntry[] = [
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เบญจมาศ", typeEn: "Chrysanthemum", variant: "มูลันสีชมพู", variantEn: "Mulan Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เบญจมาศ", typeEn: "Chrysanthemum", variant: "เรดดีสีแดง", variantEn: "Reddy Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เบญจมาศ", typeEn: "Chrysanthemum", variant: "กระดุมสีเขียว", variantEn: "Green Button" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เบญจมาศ", typeEn: "Chrysanthemum", variant: "ขาวมาเลเซียสีขาว", variantEn: "Malaysian White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เบญจมาศ", typeEn: "Chrysanthemum", variant: "เหลืองขมิ้นสีเหลือง", variantEn: "Khamin Yellow" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กุหลาบ", typeEn: "Rose", variant: "แบ็กคาร่าสีแดงเข้ม", variantEn: "Black Baccara Dark Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กุหลาบ", typeEn: "Rose", variant: "อวาลานช์สีขาว", variantEn: "Avalanche White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กุหลาบ", typeEn: "Rose", variant: "โซเฟียลอเรนสีชมพู", variantEn: "Sophia Loren Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กุหลาบ", typeEn: "Rose", variant: "ว้าวสีส้ม", variantEn: "Wow Orange" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กุหลาบ", typeEn: "Rose", variant: "ไร้หนามโครงการหลวงสีชมพูพาสเทล", variantEn: "Royal Project Thornless Pastel Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กล้วยไม้", typeEn: "Orchid", variant: "หวายสีโจแดง", variantEn: "Dendrobium Jo Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กล้วยไม้", typeEn: "Orchid", variant: "หวายสีบอมชมพู", variantEn: "Dendrobium Bom Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กล้วยไม้", typeEn: "Orchid", variant: "หวายสีขาวสนาน", variantEn: "Dendrobium Sanan White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กล้วยไม้", typeEn: "Orchid", variant: "แวนด้าสีส้ม", variantEn: "Vanda Orange" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "กล้วยไม้", typeEn: "Orchid", variant: "ออนซิเดียมสีเหลืองทอง", variantEn: "Oncidium Golden Yellow" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เยอบีร่า", typeEn: "Gerbera", variant: "เรดร็อคสีแดง", variantEn: "Red Rock Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เยอบีร่า", typeEn: "Gerbera", variant: "ดักลาสสีเหลือง", variantEn: "Douglas Yellow" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เยอบีร่า", typeEn: "Gerbera", variant: "ออโรร่าสีส้ม", variantEn: "Aurora Orange" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "เยอบีร่า", typeEn: "Gerbera", variant: "นาตาชาสีชมพู", variantEn: "Natasha Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ลิลลี่", typeEn: "Lily", variant: "คาซาบลังก้าสีขาว", variantEn: "Casablanca White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ลิลลี่", typeEn: "Lily", variant: "ซอร์บอนน์สีชมพู", variantEn: "Sorbonne Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ลิลลี่", typeEn: "Lily", variant: "ทีโบว์สีเหลือง", variantEn: "Teepee Yellow" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ปทุมมา", typeEn: "Siam Tulip", variant: "เชียงใหม่พิงค์สีชมพู", variantEn: "Chiang Mai Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ปทุมมา", typeEn: "Siam Tulip", variant: "ขาวมุกสีขาว", variantEn: "Pearl White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ปทุมมา", typeEn: "Siam Tulip", variant: "ลัดดาวรรณสีแดง", variantEn: "Laddawan Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ปทุมมา", typeEn: "Siam Tulip", variant: "ช็อคโกแลตสีน้ำตาลแดง", variantEn: "Chocolate Red-Brown" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "หน้าวัว", typeEn: "Anthurium", variant: "เปลวเทียนสีแดง", variantEn: "Plew Thian Red" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "หน้าวัว", typeEn: "Anthurium", variant: "ดารินสีชมพู", variantEn: "Darin Pink" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "หน้าวัว", typeEn: "Anthurium", variant: "ขาวดวงตาสีขาว", variantEn: "Khao Duangta White" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "หน้าวัว", typeEn: "Anthurium", variant: "เอลซ่าสีเขียว", variantEn: "Elsa Green" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "คาร์เนชัน", typeEn: "Carnation", variant: "คาร์เนชันสีชมพูคลาสสิก", variantEn: "Classic Pink Carnation" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "คาร์เนชัน", typeEn: "Carnation", variant: "คาร์เนชันสีแดงสเปน", variantEn: "Spanish Red Carnation" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "คาร์เนชัน", typeEn: "Carnation", variant: "คาร์เนชันสีส้มพีช", variantEn: "Peach Orange Carnation" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "คาร์เนชัน", typeEn: "Carnation", variant: "คาร์เนชันสีเขียวแอปเปิ้ล", variantEn: "Apple Green Carnation" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ทานตะวัน", typeEn: "Sunflower", variant: "วินเซนต์ชอยส์สีส้มทอง", variantEn: "Vincent Choice Orange-Gold" },
  { category: "ไม้ดอกหลัก", categoryEn: "Main Flowers", type: "ทานตะวัน", typeEn: "Sunflower", variant: "ซันริชสีเหลืองเข้ม", variantEn: "Sunrich Deep Yellow" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "มากาเร็ต", typeEn: "Margaret", variant: "มากาเร็ตสีม่วงเข้ม", variantEn: "Deep Purple Margaret" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "มากาเร็ต", typeEn: "Margaret", variant: "มากาเร็ตสีม่วงอ่อน", variantEn: "Light Purple Margaret" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "มากาเร็ต", typeEn: "Margaret", variant: "มากาเร็ตสีชมพู", variantEn: "Pink Margaret" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "มากาเร็ต", typeEn: "Margaret", variant: "มากาเร็ตสีขาว", variantEn: "White Margaret" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "คัตเตอร์ / พีค็อก", typeEn: "Cutter & Peacock", variant: "คัตเตอร์สีขาว", variantEn: "White Cutter" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "คัตเตอร์ / พีค็อก", typeEn: "Cutter & Peacock", variant: "พีค็อกสีม่วง", variantEn: "Purple Peacock" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "คัตเตอร์ / พีค็อก", typeEn: "Cutter & Peacock", variant: "พีค็อกสีชมพู", variantEn: "Pink Peacock" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ยิปโซ / ยิปซี", typeEn: "Gypsophila", variant: "ยิปโซสีขาว", variantEn: "White Gypsophila" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ยิปโซ / ยิปซี", typeEn: "Gypsophila", variant: "ยิปซีสีชมพู", variantEn: "Pink Gypsy" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ยิปโซ / ยิปซี", typeEn: "Gypsophila", variant: "ยิปโซย้อมสีรุ้ง", variantEn: "Rainbow Dyed Gypsophila" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแตติส", typeEn: "Statice", variant: "สแตติสสีม่วงเข้ม", variantEn: "Deep Purple Statice" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแตติส", typeEn: "Statice", variant: "สแตติสสีชมพู", variantEn: "Pink Statice" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแตติส", typeEn: "Statice", variant: "สแตติสสีเหลือง", variantEn: "Yellow Statice" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแตติส", typeEn: "Statice", variant: "สแตติสสีขาว", variantEn: "White Statice" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ไฮเดรนเยีย", typeEn: "Hydrangea", variant: "ไฮเดรนเยียสีฟ้าอ่อน", variantEn: "Light Blue Hydrangea" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ไฮเดรนเยีย", typeEn: "Hydrangea", variant: "ไฮเดรนเยียสีชมพูม่วง", variantEn: "Pink Purple Hydrangea" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "ไฮเดรนเยีย", typeEn: "Hydrangea", variant: "ไฮเดรนเยียสีขาว", variantEn: "White Hydrangea" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "อัลสโตรมีเรีย", typeEn: "Alstroemeria", variant: "อัลสโตรมีเรียสีชมพูลายเสือ", variantEn: "Tiger Pink Alstroemeria" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "อัลสโตรมีเรีย", typeEn: "Alstroemeria", variant: "อัลสโตรมีเรียสีขาวปากเหลือง", variantEn: "White Yellow Lip Alstroemeria" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "อัลสโตรมีเรีย", typeEn: "Alstroemeria", variant: "อัลสโตรมีเรียสีม่วงพาสเทล", variantEn: "Pastel Purple Alstroemeria" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแน็ปดรากอน / ปากมังกร", typeEn: "Snapdragon", variant: "สแน็ปดรากอนสีชมพูเข้ม", variantEn: "Deep Pink Snapdragon" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแน็ปดรากอน / ปากมังกร", typeEn: "Snapdragon", variant: "สแน็ปดรากอนสีเหลืองเลมอน", variantEn: "Lemon Yellow Snapdragon" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สแน็ปดรากอน / ปากมังกร", typeEn: "Snapdragon", variant: "สแน็ปดรากอนสีขาวนวล", variantEn: "Off-White Snapdragon" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "แกลดิโอลัส / ดอกซ่อนกลิ่นฝรั่ง", typeEn: "Gladiolus", variant: "แกลดิโอลัสสีแดงสด", variantEn: "Bright Red Gladiolus" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "แกลดิโอลัส / ดอกซ่อนกลิ่นฝรั่ง", typeEn: "Gladiolus", variant: "แกลดิโอลัสสีชมพูอมส้ม", variantEn: "Peach Pink Gladiolus" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "แกลดิโอลัส / ดอกซ่อนกลิ่นฝรั่ง", typeEn: "Gladiolus", variant: "แกลดิโอลัสสีเหลืองทอง", variantEn: "Golden Yellow Gladiolus" },
  { category: "ไม้แซมและไม้จัดทุ่ง", categoryEn: "Filler & Field Flowers", type: "สร้อยทอง", typeEn: "Solidago", variant: "สร้อยทองสีเหลือง", variantEn: "Solidago Yellow" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ดาวเรือง", typeEn: "Marigold", variant: "ทองเฉลิมสีเหลืองทอง", variantEn: "Thong Chaloem Golden Yellow" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ดาวเรือง", typeEn: "Marigold", variant: "ดุ๊กสีส้ม", variantEn: "Duke Orange" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ดาวเรือง", typeEn: "Marigold", variant: "มะนาวสีเหลืองอ่อน", variantEn: "Lime Light Yellow" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "บัวหลวง", typeEn: "Lotus", variant: "สัตตบุตย์สีขาว", variantEn: "Sattabuttra White" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "บัวหลวง", typeEn: "Lotus", variant: "สัตตบงกชสีชมพู", variantEn: "Sattabongkot Pink" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "บัวหลวง", typeEn: "Lotus", variant: "ประทุมสีชมพูสด", variantEn: "Prathum Bright Pink" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ดอกรัก", typeEn: "Crown Flower", variant: "ดอกรักสีขาว", variantEn: "White Crown Flower" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ดอกรัก", typeEn: "Crown Flower", variant: "ดอกรักสีม่วง", variantEn: "Purple Crown Flower" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "มะลิ", typeEn: "Jasmine", variant: "มะลิลาสีขาว", variantEn: "Mali La White" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "มะลิ", typeEn: "Jasmine", variant: "มะลิซ้อนสีขาว", variantEn: "Mali Son Double White" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ซ่อนกลิ่นไทย", typeEn: "Tuberose", variant: "ซ่อนกลิ่นดอกซ้อนสีขาว", variantEn: "Double White Tuberose" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "ซ่อนกลิ่นไทย", typeEn: "Tuberose", variant: "ซ่อนกลิ่นดอกลาสีขาว", variantEn: "Single White Tuberose" },
  { category: "ไม้ดอกวัฒนธรรมและพิธีกรรม", categoryEn: "Traditional Flowers", type: "พุด", typeEn: "Gardenia", variant: "ดอกพุดตูมสีขาว", variantEn: "Gardenia Bud White" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "ยูคาลิปตัส", typeEn: "Eucalyptus", variant: "ซิลเวอร์ดอลลาร์สีเขียวเงินใบกลม", variantEn: "Silver Dollar Eucalyptus" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "ยูคาลิปตัส", typeEn: "Eucalyptus", variant: "พาร์วิโฟเลียสีเขียวเข้มใบรี", variantEn: "Parvifolia Eucalyptus" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "เฟิร์น", typeEn: "Fern", variant: "ใบมะขามสีเขียวสด", variantEn: "Leatherleaf Fern" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "เฟิร์น", typeEn: "Fern", variant: "เฟิร์นนาคราชสีเขียวเข้ม", variantEn: "Davallia Fern" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "เฟิร์น", typeEn: "Fern", variant: "หนังขนนกสีเขียวโปร่ง", variantEn: "Asparagus Fern" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "เล็บครุฑ", typeEn: "Aralia", variant: "เล็บครุฑกระจกสีเขียวเข้ม", variantEn: "Geranium Aralia" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "เล็บครุฑ", typeEn: "Aralia", variant: "เล็บครุฑผักชีสีเขียวฝอย", variantEn: "Ming Aralia" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "หมากผู้หมากเมีย", typeEn: "Cordyline", variant: "ทับทิมสีแดงเข้ม", variantEn: "Ruby Cordyline" },
  { category: "ไม้ตัดใบและใบไม้แซมช่อ", categoryEn: "Cut Foliage", type: "หมากผู้หมากเมีย", typeEn: "Cordyline", variant: "เขียวลายทางสีเขียวสลับขาว", variantEn: "Variegated Green Cordyline" },
];

/** Distinct flower types (Type_TH), in master-list order. */
export const FLOWER_TYPES: string[] = Array.from(new Set(FLOWERS.map((f) => f.type)));

/** Varieties belonging to one type — powers the cascading Type → Variety suggestion. */
export function variantsForType(type: string): string[] {
  const t = (type ?? "").trim();
  if (!t) return Array.from(new Set(FLOWERS.map((f) => f.variant)));
  return FLOWERS.filter((f) => f.type === t).map((f) => f.variant);
}

/** All variety names (used when no type is chosen yet). */
export const FLOWER_VARIANTS: string[] = Array.from(new Set(FLOWERS.map((f) => f.variant)));

export interface PackagingMaterial {
  category: string; material: string; materialEn: string;
  unit: string; efRange: string; efDefault: number;
  lifespan: string; standardWeight: string; note: string;
}

/** 14 materials — flower_shipping_packaging_ef_list */
export const PACKAGING_MATERIALS: PackagingMaterial[] = [
  { category: "บรรจุภัณฑ์หลัก (กล่อง/ภาชนะ)", material: "ตะกร้าพลาสติกขนส่ง (HDPE - Dutch bucket style)", materialEn: "Plastic Transport Basket (HDPE)", unit: "kg CO2e / kg วัสดุ", efRange: "1.8 - 2.5", efDefault: 2.5, lifespan: "50 - 100 รอบ", standardWeight: "1.20 - 1.80 kg / ใบ", note: "ใช้ซ้ำได้หลายรอบ นิยมใช้แช่น้ำส่งดอกไม้ก้านยาว เช่น กุหลาบ ลิลลี่" },
  { category: "บรรจุภัณฑ์หลัก (กล่อง/ภาชนะ)", material: "กล่องกระดาษลูกฟูก (เยื่อใหม่ Virgin)", materialEn: "Corrugated Box (Virgin Pulp)", unit: "kg CO2e / kg วัสดุ", efRange: "0.91 - 1.14", efDefault: 1.05, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.30 - 0.70 kg / กล่อง", note: "น้ำหนักขึ้นอยู่กับขนาดกล่องและความหนาของลอน" },
  { category: "บรรจุภัณฑ์หลัก (กล่อง/ภาชนะ)", material: "กล่องกระดาษลูกฟูก (เยื่อรีไซเคิล Recycled)", materialEn: "Corrugated Box (Recycled Pulp)", unit: "kg CO2e / kg วัสดุ", efRange: "0.73 - 0.82", efDefault: 0.82, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.30 - 0.70 kg / กล่อง", note: "เป็นมิตรต่อสิ่งแวดล้อมมากกว่า แต่ความแข็งแรงต่อความชื้นลดลงเล็กน้อย" },
  { category: "วัสดุห่อหุ้มและกันกระแทก", material: "แผ่นพลาสติกใส/ซองห่อช่อดอกไม้ (OPP / PE Film)", materialEn: "Clear Plastic Wrapping Sleeve (OPP / PE Film)", unit: "kg CO2e / kg วัสดุ", efRange: "2.0 - 3.5", efDefault: 2.5, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.005 - 0.015 kg / แผ่น", note: "ใช้ห่อช่อดอกไม้เพื่อความสวยงามและป้องกันกลีบดอกช้ำ" },
  { category: "วัสดุห่อหุ้มและกันกระแทก", material: "ถุงพลาสติกหูหิ้ว/ถุงคุมอุณหภูมิ (LDPE)", materialEn: "Plastic Bag (LDPE)", unit: "kg CO2e / kg วัสดุ", efRange: "2.0 - 3.0", efDefault: 2.2, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.010 - 0.040 kg / ใบ", note: "ใช้ใส่กำดอกไม้ขายส่ง หรือรองก้นตะกร้าเพื่อขังน้ำ" },
  { category: "วัสดุห่อหุ้มและกันกระแทก", material: "กระดาษคราฟท์ห่อช่อ / กระดาษรังผึ้งกันกระแทก", materialEn: "Kraft Wrapping Paper / Honeycomb Cushioning", unit: "kg CO2e / kg วัสดุ", efRange: "0.70 - 0.95", efDefault: 0.85, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.015 - 0.035 kg / แผ่น", note: "วัสดุทดแทนพลาสติกยอดนิยมสำหรับแบรนด์รักษ์โลก" },
  { category: "วัสดุห่อหุ้มและกันกระแทก", material: "กระดาษหนังสือพิมพ์ / กระดาษฉีกรองก้นกล่อง", materialEn: "Newsprint / Shredded Paper Filler", unit: "kg CO2e / kg วัสดุ", efRange: "0.50 - 0.73", efDefault: 0.65, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.050 - 0.150 kg / กล่อง", note: "ใช้ขยำรองก้นกล่องหรือห่อหุ้มกำดอกไม้เพื่อซับความชื้น" },
  { category: "วัสดุผูกยึดและปิดผนึก", material: "เทปกาวพลาสติกปิดกล่อง (OPP Tape)", materialEn: "Plastic Packaging Tape (OPP)", unit: "kg CO2e / เมตร", efRange: "0.01 - 0.03", efDefault: 0.02, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.002 - 0.005 kg / เมตร", note: "คำนวณตามความยาวที่ใช้จริงต่อกล่อง (เฉลี่ยกล่องละ 1-2 เมตร)" },
  { category: "วัสดุผูกยึดและปิดผนึก", material: "เทปกาวกระดาษคราฟท์ (Kraft Paper Tape)", materialEn: "Kraft Paper Packaging Tape", unit: "kg CO2e / เมตร", efRange: "0.005 - 0.015", efDefault: 0.01, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.002 - 0.004 kg / เมตร", note: "ย่อยสลายง่าย รีไซเคิลพร้อมกล่องลูกฟูกได้เลย" },
  { category: "วัสดุผูกยึดและปิดผนึก", material: "เชือกฟางพลาสติก (PP Straw Rope)", materialEn: "Plastic Straw Rope (PP)", unit: "kg CO2e / เมตร", efRange: "0.01 - 0.02", efDefault: 0.015, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.001 - 0.003 kg / เมตร", note: "นิยมใช้มัดกำดอกไม้สดและผูกกล่องขนส่งขนาดใหญ่" },
  { category: "วัสดุผูกยึดและปิดผนึก", material: "เชือกปอ / เชือกป่านธรรมชาติ (Jute Twine)", materialEn: "Natural Jute Twine", unit: "kg CO2e / เมตร", efRange: "0.002 - 0.006", efDefault: 0.004, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.001 - 0.002 kg / เมตร", note: "เชือกใยธรรมชาติ คาร์บอนต่ำมาก นิยมใช้ผูกช่อสไตล์มินิมอล" },
  { category: "วัสดุรักษาคุณภาพและความสด", material: "โอเอซิส / โฟมปักดอกไม้ (Floral Foam)", materialEn: "Floral Foam (Oasis)", unit: "kg CO2e / ก้อนมาตรฐาน", efRange: "0.15 - 0.35", efDefault: 0.25, lifespan: "1 รอบ (ใช้ครั้งเดียว)", standardWeight: "0.040 - 0.050 kg / ก้อน", note: "เป็นไมโครพลาสติกที่ไม่ย่อยสลาย มีค่า EF สูงเมื่อเทียบกับน้ำหนักแห้ง" },
  { category: "วัสดุรักษาคุณภาพและความสด", material: "หลอดน้ำเลี้ยงก้านดอกไม้ (Water Tubes/Vials)", materialEn: "Plastic Flower Water Tubes/Vials", unit: "kg CO2e / ชิ้น", efRange: "0.015 - 0.030", efDefault: 0.022, lifespan: "1 รอบ (reuse ได้ถ้าเก็บคืน)", standardWeight: "0.003 - 0.006 kg / ชิ้น", note: "หลอดพลาสติกพร้อมฝายางสำหรับสวมโคนก้านเดี่ยวเพื่อขังน้ำเลี้ยง" },
  { category: "วัสดุรักษาคุณภาพและความสด", material: "เจลเก็บความเย็น / ไอซ์แพค", materialEn: "Cool Gel Pack / Ice Pack", unit: "kg CO2e / ชิ้น", efRange: "0.05 - 0.15", efDefault: 0.08, lifespan: "ใช้ซ้ำได้ (ระบบปิด)", standardWeight: "0.100 - 0.400 kg / ชิ้น", note: "ใช้ควบคุมอุณหภูมิในกล่องระหว่างขนส่งดอกไม้เมืองหนาว" },
];

export interface VehicleFuel {
  category: string; vehicle: string; vehicleEn: string;
  fuel: string; fuelEn: string;
  vehicleKey: string; fuelKey: string;
}

/** 23 vehicle x fuel pairs — vehicle_and_fuel_mapping_list.
 *  NOTE: KYN supplied the mapping/enum only — EF_tkm / EF_vkm values are NOT in the file
 *  and must be obtained from KYN or TGO before the transport formula can use them. */
export const VEHICLE_FUELS: VehicleFuel[] = [
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ขนาดเล็ก", vehicleEn: "Eco Car / Sedan", fuel: "แก๊สโซฮอล์ 91 / 95 (E10)", fuelEn: "Gasohol 91 / 95 (E10)", vehicleKey: "sedan", fuelKey: "E10" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ขนาดเล็ก", vehicleEn: "Eco Car / Sedan", fuel: "แก๊สโซฮอล์ E20", fuelEn: "Gasohol E20", vehicleKey: "sedan", fuelKey: "E20" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ขนาดเล็ก", vehicleEn: "Eco Car / Sedan", fuel: "แก๊สโซฮอล์ E85", fuelEn: "Gasohol E85", vehicleKey: "sedan", fuelKey: "E85" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ขนาดเล็ก", vehicleEn: "Eco Car / Sedan", fuel: "น้ำมันเบนซินไร้สารตะกั่ว", fuelEn: "Pure Gasoline", vehicleKey: "sedan", fuelKey: "gasoline" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์อเนกประสงค์", vehicleEn: "SUV / PPV", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "suv", fuelKey: "B7" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ไฟฟ้า (EV)", vehicleEn: "Battery EV", fuel: "ไฟฟ้า 100% (Battery EV)", fuelEn: "Electricity (EV)", vehicleKey: "ev_passenger", fuelKey: "EV" },
  { category: "รถยนต์ส่วนบุคคล", vehicle: "รถยนต์ไฮบริด / ปลั๊กอินไฮบริด", vehicleEn: "HEV / PHEV", fuel: "แก๊สโซฮอล์ 91 / 95 (E10)", fuelEn: "Gasohol 91 / 95 (E10)", vehicleKey: "phev_hev", fuelKey: "E10" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถกระบะบรรทุก 4 ล้อ", vehicleEn: "Pick-up Truck", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "pickup", fuelKey: "B7" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถกระบะบรรทุก 4 ล้อ", vehicleEn: "Pick-up Truck", fuel: "ดีเซล B10", fuelEn: "Diesel B10", vehicleKey: "pickup", fuelKey: "B10" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถกระบะบรรทุก 4 ล้อ", vehicleEn: "Pick-up Truck", fuel: "ดีเซล B20", fuelEn: "Diesel B20", vehicleKey: "pickup", fuelKey: "B20" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถกระบะบรรทุก 4 ล้อ", vehicleEn: "Pick-up Truck", fuel: "CNG / NGV", fuelEn: "CNG / NGV", vehicleKey: "pickup", fuelKey: "CNG" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถกระบะบรรทุก 4 ล้อ", vehicleEn: "Pick-up Truck", fuel: "LPG", fuelEn: "LPG", vehicleKey: "pickup", fuelKey: "LPG" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถตู้ขนส่งพัสดุ", vehicleEn: "Cargo Van", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "van", fuelKey: "B7" },
  { category: "รถบรรทุกขนาดเล็กและรถตู้", vehicle: "รถอเนกประสงค์ขนาดเล็ก", vehicleEn: "Light Motor Vehicle (LMV)", fuel: "แก๊สโซฮอล์ 91 / 95 (E10)", fuelEn: "Gasohol 91 / 95 (E10)", vehicleKey: "lmv", fuelKey: "E10" },
  { category: "รถบรรทุกขนาดใหญ่", vehicle: "รถบรรทุก 6 ล้อ", vehicleEn: "6-wheeler Truck", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "6_wheeler", fuelKey: "B7" },
  { category: "รถบรรทุกขนาดใหญ่", vehicle: "รถบรรทุก 10 ล้อ", vehicleEn: "10-wheeler Truck", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "10_wheeler", fuelKey: "B7" },
  { category: "รถพ่วงและรถกึ่งพ่วง", vehicle: "รถลากพ่วง", vehicleEn: "Full Trailer", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "full_trailer", fuelKey: "B7" },
  { category: "รถพ่วงและรถกึ่งพ่วง", vehicle: "รถกึ่งพ่วง", vehicleEn: "Semi-Trailer", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "semi_trailer", fuelKey: "B7" },
  { category: "รถโดยสาร", vehicle: "รถโดยสารประจำทาง / รถทัวร์", vehicleEn: "Standard Bus", fuel: "ดีเซล B7", fuelEn: "Diesel B7", vehicleKey: "bus", fuelKey: "B7" },
  { category: "รถจักรยานยนต์", vehicle: "รถจักรยานยนต์ขนส่งพัสดุ", vehicleEn: "Delivery Motorcycle", fuel: "แก๊สโซฮอล์ 91 / 95 (E10)", fuelEn: "Gasohol 91 / 95 (E10)", vehicleKey: "motorcycle", fuelKey: "E10" },
  { category: "รถจักรยานยนต์", vehicle: "รถจักรยานยนต์ขนส่งพัสดุ", vehicleEn: "Delivery Motorcycle", fuel: "แก๊สโซฮอล์ E20", fuelEn: "Gasohol E20", vehicleKey: "motorcycle", fuelKey: "E20" },
  { category: "รถจักรยานยนต์", vehicle: "รถจักรยานยนต์ขนส่งพัสดุ", vehicleEn: "Delivery Motorcycle", fuel: "ไฟฟ้า 100% (Battery EV)", fuelEn: "Electricity (EV)", vehicleKey: "motorcycle_ev", fuelKey: "EV" },
  { category: "ระบบไฮบริด / สองเชื้อเพลิง", vehicle: "น้ำมัน สลับ ก๊าซ", vehicleEn: "Bi-Fuel (Gasoline + LPG/NGV)", fuel: "ระบบเชื้อเพลิงสองระบบ", fuelEn: "Bi-Fuel", vehicleKey: "bi_fuel", fuelKey: "bi_fuel" },
];
